cc-notification-service:
  cose:
    key-identifier: "2E5DCD3F4DF33B16"
  cache-duration: 21600000
  monitor:
    prometheus:
      user: "prometheus"
      password: ${vcap.services.cc_prometheus.credentials.password}
  pdf:
    show-watermark: false

  allowed-origin: "https://www.covidcertificate.admin.ch"

cc-signing-service:
  url: "https://covidcertificate-signing.bag.admin.ch/bag-vaccinecer-webapp/sign"
  verify-url: "https://covidcertificate-signing.bag.admin.ch/bag-vaccinecer-webapp/sign/verify"
  kid-url: "https://covidcertificate-signing.bag.admin.ch/bag-vaccinecer-webapp/sign/configuration/kid"

cc-printing-service:
  url: "https://cc-printing-service.app.cfap02.atlantica.admin.ch/api/v1/print"

cc-inapp-delivery-service:
  url: "https://ch-covidcertificate-backend-delivery-ws.app.cfap02.atlantica.admin.ch/cgs/delivery/v1/covidcert"

ch-covidcertificate-backend-verifier-service:
  url: "https://ch-covidcertificate-backend-verifier-ws.app.cfap02.atlantica.admin.ch/dcga/v1/valueSets"

## Mutual-SSL configuration
app:
  conn:
    cc-signing-service:
      key-store: ${vcap.services.cc_signing_service_keystore.credentials.keystore}
      key-store-password: ${vcap.services.cc_signing_service_keystore.credentials.keystorePassword}
      key-alias: cc-notification-service
      key-password: ${vcap.services.cc_signing_service_keystore.credentials.keyPassword}
      trust-store: ${vcap.services.cc_signing_service_keystore.credentials.keystore}
      trust-store-password: ${vcap.services.cc_signing_service_keystore.credentials.keystorePassword}
