spring:
  security:
    oauth2:
      client:
        registration:
          cc-notification-service:
            client-id: "cc-notification-service"
            client-secret: ${vcap.services.cc-notification-service-keycloak-client.credentials.client-secret}
            authorization-grant-type: "client_credentials"
            provider: "default-provider"
            scope: "openid"
        provider:
          default-provider:
            issuer-uri: "https://identity-a.bit.admin.ch/realms/BAG-CovidCertificate"

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "https://identity-a.bit.admin.ch/realms/BAG-CovidCertificate"

cc-notification-service:
  # TODO: Muss noch angefordert werden.
  monitor:
    prometheus:
      user: "prometheus"
      password: ${vcap.services.cc_prometheus.credentials.password}

  allowed-origin: "https://www.covidcertificate-a.admin.ch"

cc-management-service:
  uri: "https://cc-management-service.abn.app.cfap02.atlantica.admin.ch/"